#!/bin/bash

if [[ "$@" == *"-h"* ]]
then
    echo "Delitele od Slavka Routy" 
    echo "Pouziti: delitele <int> [argumenty]"
    echo "(int - cele cislo) Argumenty - '-p' zobraz pouzita prvocisla, '-h' zobrazi tuto napovedu"
    exit
elif [[ "$@" == "" || "$@" == " " ]]
then
    echo "Pouziti: delitele <int> [argumenty]"
    echo "(int - cele cislo) Argumenty - '-p' zobraz pouzita prvocisla, '-h' zobrazi tuto napovedu"
    exit
fi

num=$1
z=$num
prvocisla=""
delitele=""
m=$(($1/2))

for ((x=2; x<=$m; x++))
do
    je_prvocislo=true
    for ((y=2; y<=x; y++))
    do
        if [ $((x % y)) -eq 0 ]
        then
            je_prvocislo=false
            break
        fi
    done
    if [ $je_prvocislo ]
    then
        while [ $((z % x)) -eq 0 ]
        do
            delitele+="$x "
            z=$((z/x))
        done
        prvocisla+="$x "
    fi
done

if [ "$2" == "-p" ]
then
    echo "Prvocisla do poloviny + 1 zadaneho cisla: $prvocisla"
fi

if [ ${#delitele} == 0 ]
then
    echo "Cislo $1 je prvocislo"
else
    echo "Cislo $1 lze rozdelit na: $delitele"
fi